version: '3'
services:
  app:
    build: ./app
    image: app
    ports:
     - 3000:3000
    environment:
      - PORT=3000
      - REDIS_PORT=6379
  # redis:
  #   image: "redis:6.2"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "./redis/data/redis:/data"
